require: rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - '*/vendor/**/*'
    - 'db/schema.rb'

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AndOr:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/NamedSubject:
  Enabled: false
